# yamllint disable rule:line-length
---
name: Releasability status
on:
  workflow_run:
    workflows: [ "Build" ]  # Name must match the name of the build workflow
    types: [ completed ]
    branches:
      - master
      - branch-*
      - dogfood-*

jobs:
  update_releasability_status:
    runs-on: github-ubuntu-latest-s
    name: Releasability status
    permissions:
      id-token: write
      statuses: write
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: SonarSource/gh-action_releasability/releasability-status@v3
        with:
          optional_checks: "Jira"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
